services:
  ui:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    env_file:
      - .env
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${LISTEN_IP}:${UI_LISTEN_PORT}:8501
    volumes:
      - ./:/app
    command: ./entrypoint-ui.sh

  api:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    env_file:
      - .env
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${LISTEN_IP}:${API_LISTEN_PORT}:8502
    volumes:
      - ./:/app
    command: ./entrypoint-api.sh