volumes:
  was-storage:
services:
  was:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    environment:
      - WAS_IP
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${LISTEN_IP}:${UI_LISTEN_PORT}:8502
      - ${LISTEN_IP}:${API_LISTEN_PORT}:8502
    volumes:
      - ./:/app
      - ./storage:/app/storage
