services:
  was:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    environment:
      - LOG_LEVEL
      - TZ=${TZ}
      - WAS_IP
      - WAS_LOG_LEVEL
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${LISTEN_IP}:${API_LISTEN_PORT}:8502
    volumes:
      - ./:/app
      - ./storage:/app/storage
